name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Backend lint & test
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Lint backend
        run: golangci-lint run ./backend/...
      - name: Test backend
        run: go test ./backend/...

      # Frontend lint & test
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      - name: Test frontend
        run: |
          cd frontend
          npm test -- --watchAll=false
          