name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      # Step 3: Install golangci-lint
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      # Step 4: Lint backend
      - name: Lint backend
        run: golangci-lint run ./backend --timeout 5m

      # Step 5: Test backend
      - name: Test backend
        run: go test ./backend/...