name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Backend lint & test
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Lint backend
        run: golangci-lint run ./backend --timeout 5m -v

      - name: Test backend
        run: go test ./backend/...

      - name: Debug file structure
        run: |
          echo "Listing backend directory:"
          ls -R ./backend
          echo "Contents of go.mod:"
          cat ./backend/go.mod || echo "No go.mod found"
          echo "Running go mod tidy:"
          cd ./backend && go mod tidy || echo "go mod tidy failed"

      - name: Check Go version
        run: go version

      # Frontend lint & test
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Test frontend
        run: |
          cd frontend
          npm test -- --watchAll=false
